name: Demo

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc:
    uses: stoe-actions-playground/oidc-demo/.github/workflows/vault.yml@main
    with:
      AZURE_KEYVAULT_NAME: ${{ vars.AZURE_KEYVAULT_NAME }}
      AZURE_SECRET_NAME: ${{ vars.AZURE_SECRET_NAME }}
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  demo:
    runs-on: ubuntu-latest
    needs: oidc

    steps:
      - name: Print the secret
        run: |
          echo "The secret is: ${{ needs.oidc.outputs.vaultsecret }}"
